### ISSUE TITLE
GNU/Linux için Kurulum Betiği 

### ISSUE THREAD

**Issue by beucismis** [qabRieL99/TerrariaTurkish#7]
Merhaba, GNU/Linux kullanıcsıyım. Kurulum için derlenmiş, çalıştırabilir bir dosya (.exe) kullandığınızı gördüm. Doğrduan bu uzantılı bir dosyayı çalıştırmak pek mümkün değil helede Windows bağımlılıkları içeriyorsa... Çalıştırabilir dosya içerisinde ne gibi işlemler yapıyorsunuz? Yaptığınız işlemlere göre Python ya da Bash ile GNU/Linux'da oyunu oynayanlar ve Türkçe çeviriyi kurmak isteyenler için betik hazırlayabilirim.

**Comment by qabRieL99** [comment]
Merhabalar,
Orijinali trigger-segfault tarafından hazırlanmış bir yamalama programının tarafımca modifiye edilmiş sürümünü kullanıyorum kurulum için. Kaynak kodlarını [şurada](https://github.com/qabRieL99/TerrariaLocalizationPacker) bulabilirsin.
Linux tarafında hiçbir deneyimim olmadığı için (Windows tarafında da pek olduğu sayılmaz) fazladan bir şey söyleyemiyorum. 😞

**Comment by beucismis** [comment]
Merhaba, uzun zaman oldu... Dönüş yapmadığım için özür dilerim zira aklımdan tamamen çıkmış. Bahsettiğin projeye göz attım ama pek anlamadım. Oyunun dosyalarını taradım ama *location* dosyalarını nerede tutuyor en ufak fikrim yok...

**Comment by qabRieL99** [comment]
Sıkıntı yok insanlık hali. Yamanın içinde bulunan .json dosyaları, normalde Terraria.exe uygulamasının içinde gömülü bir şekilde bulunuyor. Terraria Localization Packer ile bu dosyaları çıkartıp, değiştirip, oyuna tekrar ekleyebiliyoruz. Gerekli eylem şurada gerçekleşiyor:

https://github.com/qabRieL99/TerrariaLocalizationPacker/blob/master/TerrariaLocalizationPacker/Patching/LocalizationPacker.cs#L62-L146

**Comment by beucismis** [comment]
Teşekkür ederim. İnceleyeceğim.

**Comment by qabRieL99** [comment]
Çeviriyi Steam atölye şeklinde guncelledim, Linux'da mevcut mu bu sistem?

**Comment by beucismis** [comment]
Evet mevcut.

**Comment by qabRieL99** [comment]
Deneyin çalışıyor mu bakalım.

**Comment by beucismis** [comment]
Denedim, bir sorun göremedim. İyi çalışıyor. Teşekkür ederim :)

Atölye öğesi: [https://steamcommunity.com/sharedfiles/filedetails/?id=2441453094](https://steamcommunity.com/sharedfiles/filedetails/?id=2441453094l)
